spring:
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      routes:
        - id: SecurityApplication
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/**
          metadata:
            cors:
              allowedOrigins: "*"
              allowedMethods:
                - GET
                - POST
                - PUT
                - PATCH
                - DELETE
                - OPTIONS
              allowedHeaders: "*"
              maxAge: 30
        - id: DemoApplication
          uri: http://localhost:8087
          predicates:
            - Path=/car/**
          metadata:
            cors:
              allowedOrigins: "*"
              allowedMethods:
                - GET
                - POST
                - PUT
                - PATCH
                - DELETE
                - OPTIONS
              allowedHeaders: "*"
              maxAge: 30
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true